[PREPROCESSING]
# Pre-processing configuration
image_size = [128, 128]
# Source image size
target_diagnosis = ["Atelectasis", "Effusion", "Infiltration", "No Finding"]
# Diagnosis to process. All other discarded
keep_diagnosis = "No Finding"
# Diagnosis to be unchanged during label corruption process. Other labels will be converted to this diagnosis

[RUN]
# RUN configuration
corruption.end = 65
# Maximum corruption percentage (not including)
corruption.step = 5
# Corruption step
reduction.end = 100
# Dataset reduction percentage (not including)
reduction.step = 5
# Redcution step

[DATASET]
# Dataset configuration
seed = 123456789
# Seed for numpy random operations
num_of_worker = 2
# Prefetch workers"""
validation_fraction = 0.3
# Relative validation dataset size
test_images = 50
# Number of test images

[PLOT]
# PLOT settings
dpi = 300
# Plots DPI
size = [10, 10]
# Plot size in inches
font_size = 14

[AUGMENTATION]
rotation_angle = 5.0
# Rotate image in range [degrees]
width_shift_range = 0.05
# Shift image horizontally in range [%]
height_shift_range = 0.1
# Vertical shift range - [%]
zoom_range = 0.1
# Zoom range

[FOLDERS]
# File and folder location
root_folder = "@path @format {env[DATA_ROOT]}/data"
# Folder with dataset sets
raw_folder = "@path @format {this.folders.root_folder}/images"
# FOlder with source images"""
cooked_folder = "@path @format {this.folders.root_folder}/tmpfs/cooked"
# Folder with preprocessed files"""
validation_folder = "@path @format {this.folders.root_folder}/tmpfs/validation"
# Folder with validation files"""
test_folder = "@path @format {this.folders.root_folder}/tmpfs/test"
# Folder with preprocessed files"""
reports_folder = "@path @format {this.folders.root_folder}/reports"
# Folder with reports information"""

[LENET5]
# LeNet-5 configuration
scheduler.factor = 0.1
scheduler.patience = 3
optimizer.learning_rate = 0.001
earlystop.patience = 8
earlystop.start_epoch = 20
epochs = 100
batch_size = 32

[VGG16]
# VGG-16 configuration
scheduler.factor = 0.1
scheduler.patience = 3
optimizer.learning_rate = 0.001
optimizer.weight_decay = 0.005
optimizer.momentum = 0.9
earlystop.patience = 3
earlystop.start_epoch = 30
epochs = 100
batch_size = 32

[RESNET50]
# ResNet-50 configuration
scheduler.factor = 0.1
scheduler.patience = 3
optimizer.learning_rate = 0.001
earlystop.patience = 3
earlystop.start_epoch = 30
epochs = 100
batch_size = 32

[VIT]
# Visual Transformer configuration
scheduler.factor = 0.1
scheduler.patience = 5
optimizer.learning_rate = 0.001
earlystop.patience = 3
earlystop.start_epoch = 40
epochs = 200
batch_size = 32
patch_size=16
num_classes=4
dim=768
depth=6
heads=16
mlp_dim=3072
dropout=0.1
emb_dropout=0.1

[ALEXNET]
# AlexNet configuration
scheduler.factor = 0.1
scheduler.patience = 3
optimizer.learning_rate = 0.001
earlystop.patience = 3
earlystop.start_epoch = 30
epochs = 100
batch_size = 32

[EFFICIENTNET]
# EfficientNet configuration
scheduler.factor = 0.1
scheduler.patience = 3
optimizer.learning_rate = 0.001
earlystop.patience = 3
earlystop.start_epoch = 30
epochs = 100
batch_size = 32
dropout = 0.4
